### ISSUE TITLE
 SYSTEM ERROR 

### ISSUE THREAD

**Issue by mamidisoujanya** [aflnet/aflnet#1]
hi 
i am trying to do fuzzing for light-ftp protocol but i am getting system error please help me to resolve this error 

sudo afl-fuzz -d -i ~/AFLNET/aflnet/tutorials/lightftp/in-ftp -o out-lightftp -N tcp://127.0.0.1/2200 -x ~/AFLNET/aflnet/tutorials/lightftp/ftp.dict -P FTP -D 10000 -q 3 -s 3 -E -R -c ./ftpclean.sh ./fftp fftp.conf 2200
afl-fuzz 2.56b by <lcamtuf@google.com>
[+] You have 16 CPU cores and 3 runnable tasks (utilization: 19%).
[+] Try parallel jobs - see /usr/local/share/doc/afl/parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[*] Checking core_pattern...
[*] Checking CPU scaling governor...
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning '/home/soujanyaa/AFLNET/aflnet/tutorials/lightftp/in-ftp'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Loading extra dictionary from '/home/soujanyaa/AFLNET/aflnet/tutorials/lightftp/ftp.dict' (level 0)...
[+] Loaded 32 extra tokens, size range 3 B to 4 B.
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,orig:ftp_requests_full_anonymous.raw'...
[*] Spinning up the fork server...
[+] All right - fork server is up.

[-]  SYSTEM ERROR : AFLNet - the states hashtable should always contain an entry of the initial state
    Stop location : update_state_aware_variables(), afl-fuzz.c:910
       OS message : No such process

**Comment by thuanpv** [comment]
Thank you for reporting this issue.

Please try to follow the tutorial on a clean VM running Ubuntu 16.04 and use ubuntu as its default username and password. It should fix this issue. Note that, "ubuntu" must be the default user, the issue may not be fixed if you just add a new user. 

I will try to find the root cause and fix it so it can work on all environments and setups later.

**Comment by mamidisoujanya** [comment]
Thanks for giving replay.
for light-ftp i didn't found any crashes 
for RTSP(live555) getting Segmentation faults please help me to resolve this error 


ubuntu@ubuntu-VirtualBox:~/WORKDIR/live555/testProgs$ ~/AFLNET/aflnet/afl-fuzz -d -i ~/AFLNET/aflnet/tutorials/live555/in-rtsp -o out-live555 -N tcp://127.0.0.1/8554 -x ~/AFLNET/aflnet/tutorials/live555/rtsp.dict -P RTSP -D 10000 -q 3 -s 3 -t 5 -E -K -R ./testOnDemandRTSPServer 8554
afl-fuzz 2.56b by <lcamtuf@google.com>
[+] You have 1 CPU core and 4 runnable tasks (utilization: 400%).
[*] Checking core_pattern...
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning '/home/ubuntu/AFLNET/aflnet/tutorials/live555/in-rtsp'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Loading extra dictionary from '/home/ubuntu/AFLNET/aflnet/tutorials/live555/rtsp.dict' (level 0)...
[+] Loaded 24 extra tokens, size range 3 B to 16 B.
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,orig:rtsp_requests_aac.raw'...
[*] Spinning up the fork server...
[+] All right - fork server is up.
    len = 515, map size = 68, exec speed = 16741111 us
[*] Attempting dry run with 'id:000001,orig:rtsp_requests_ac3.raw'...
    len = 515, map size = 68, exec speed = 17444979 us
[!] WARNING: No new instrumentation output, test case may be useless.
[*] Attempting dry run with 'id:000002,orig:rtsp_requests_mkv.raw'...
    len = 896, map size = 68, exec speed = 19782479 us
[!] WARNING: No new instrumentation output, test case may be useless.
[*] Attempting dry run with 'id:000003,orig:rtsp_requests_mp3.raw'...
    len = 668, map size = 68, exec speed = 16818736 us
[!] WARNING: No new instrumentation output, test case may be useless.
[*] Attempting dry run with 'id:000004,orig:rtsp_requests_mpg.raw'...
    len = 926, map size = 68, exec speed = 19225992 us
[!] WARNING: No new instrumentation output, test case may be useless.
[*] Attempting dry run with 'id:000005,orig:rtsp_requests_wav.raw'...
    len = 668, map size = 68, exec speed = 18708987 us
[!] WARNING: No new instrumentation output, test case may be useless.
[*] Attempting dry run with 'id:000006,orig:rtsp_requests_webm.raw'...
    len = 876, map size = 68, exec speed = 18343734 us
[!] WARNING: No new instrumentation output, test case may be useless.
[+] All test cases processed.

[!] WARNING: The target binary is pretty slow! See docs/perf_tips.txt.
[!] WARNING: Some test cases look useless. Consider using a smaller set.
[+] Here are some useful stats:

    Test case count : 1 favored, 0 variable, 7 total
       Bitmap range : 68 to 68 bits (average: 68.00 bits)
        Exec timing : 16.7M to 19.8M us (average: 18.2M us)

[+] All set and ready to roll!
Segmentation fault

**Comment by mamidisoujanya** [comment]
Thanks for giving replay

**Comment by mamidisoujanya** [comment]
Thanks for giving replay

**Comment by thuanpv** [comment]
It seems that the issue is fixed so I close it. I have also uploaded a Dockerfile for fuzzing LightFTP.

**Comment by B1y0nd** [comment]
@mamidisoujanya 
-m none!!!
command line: afl-fuzz -d -i $AFLNET/tutorials/lightftp/in-ftp -o out-lightftp -m none -N tcp://127.0.0.1/2200 -x $AFLNET/tutorials/lightftp/ftp.dict -P FTP -D 10000 -q 3 -s 3 -E -R -c ./ftpclean.sh ./fftp fftp.conf 2200
Reference1：https://blog.csdn.net/weixin_46483787/article/details/129050230
Reference2：https://blog.csdn.net/qq_28584889/article/details/121207149
