### ISSUE TITLE
Errors in afl-llvm-pass.so.cc while running the 'make' comand in llvm_mode directory

### ISSUE THREAD

**Issue by aysh494** [aflnet/aflnet#106]
Following errors pop up when I try to run make command in the llvm_mode folder:

![image](https://github.com/aflnet/aflnet/assets/143906924/f3d139ef-22db-4d1a-9234-6eaf557ec272)

Kindly please suggest the solution.

**Comment by aysh494** [comment]
![image](https://github.com/aflnet/aflnet/assets/143906924/946c6338-a572-4c58-99b4-f813649df068)

THese are some more errors.

**Comment by Marti2203** [comment]
Hi, I see you are trying to build AFLNet locally. AFLNet is built on top of a version of AFL, whose LLVM compilation pass is based on the older versions of the LLVM interface. From the Images you have provided, I see you are trying to compile with LLVM 14, which unfortunately, is too new. I would suggest using the Dockerfile to build an image where you can experiment with the tool.

**Comment by aysh494** [comment]
Hi,
Thank you for connecting.
I figured that out then and was able to build it successfully.

**Comment by Karthikdasari0423** [comment]
@aysh494 I am also facing similar issue when i tried to build locally
Could you pls suggest how did you built sucessfully?

**Comment by aysh494** [comment]
Hi Karthik, Sorry for the late reply.
I was facing this issue because I was using an LLVM version not compatible
with AFLNET.
Switching to the older version worked for me, I guess the version that
worked for me was 14-something.
i hope it helps

**Comment by aysh494** [comment]
Sorry, Just checked.
The version that worked for me was, llvm-config-6.0
This version may vary according to your ubuntu version but it should be
less than 12.

**Comment by Karthikdasari0423** [comment]
Sure, will try that
Thanks @aysh494
