### ISSUE TITLE
editing error

### ISSUE THREAD

**Issue by ruikangPeng** [aflnet/aflnet#107]
hi，author
I just discovered an editing error in [readme.md](https://github.com/aflnet/aflnet/tree/master/tutorials/network-namespace#step-1-fuzzing)
![1693808336646](https://github.com/aflnet/aflnet/assets/104423880/075adb63-37a2-4760-9dbf-2e336d51e121)

**Comment by thuanpv** [comment]
Thanks @ruikangPeng . Now it is fixed https://github.com/aflnet/aflnet/commit/2409f9086947186609454cc6ddb2e29875718ffd so I close this issue.
