### ISSUE TITLE
A question about state coverage

### ISSUE THREAD

**Issue by B1y0nd** [aflnet/aflnet#108]
We have noticed that your paper compares the state coverage. We want to know how to obtain state coverage information during the fuzzing process.
It seems that gcovr cannot obtain state coverage information and can only obtain other code coverage information, such as branch coverage and path coverage.
Looking forward to your reply.

**Comment by thuanpv** [comment]
Hi @B1y0nd,

In our paper, we replayed all the test cases and captured the unique number of response code as #states.

It means that we needed to update the code of BooFuzz so that we could store its test cases in the form that is replayable.

I hope it is clear.

Thuan

**Comment by milinbhade1214** [comment]
We want to why server code is instrumented using afl when from server we get only the responses and no other information about branch coverage?
Is only way to capture branch coverage is through tools like gcovr?
How are we measuring the branch information here?
