### ISSUE TITLE
How to debug and analyze crashes obtained by running AFLNET?

### ISSUE THREAD

**Issue by Blair-Cheng** [aflnet/aflnet#111]
How to debug and analyze crashes obtained by running AFLNET? According to AFL's debugging method, I cannot succeed on AFLNET. Is there any documentation on debugging? Thank you so much

**Comment by thuanpv** [comment]
Hi @Blair-Cheng,

You can either run aflnet with gdb or if you have bug-triggering test cases you can run them with aflnet-replay.

I hope it helps.

Thuan
