### ISSUE TITLE
AFL++ -U (unicorn mode) not available in AFLNet

### ISSUE THREAD

**Issue by bond187** [aflnet/aflnet#114]
Hello! I am attempting to use AFLNet to fuzz a network protocol running on firmware in an emulated machine (using FirmWire). The basic AFL++ fuzzer has support for unicorn, but it seems that AFLNet has removed that functionality. Is there a reason for this, and can it be reintroduced? I'd be happy to work on it myself if I knew whether it was worthwhile. Thank you!

**Comment by thuanpv** [comment]
Hi,

AFLNet was built on top of AFL, not AFL++ so it misses several features in AFL++.

We are more than happy to accept pull requests to port AFLNet to AFL++.

Regards,

Thuan
