### ISSUE TITLE
seeds initial

### ISSUE THREAD

**Issue by ruikangPeng** [aflnet/aflnet#116]
hi，author.
Sorry to bother you so much. I would like to inquire about how to obtain your initial seed?  For example: [ live555 seeds](https://github.com/aflnet/aflnet/tree/master/tutorials/live555/in-rtsp)

**Comment by thuanpv** [comment]
Hi,

Please follow the tutorial in our README.md file. Basically, you capture the real traffics and turn them into seeds using wireshark.

Thuan
