### ISSUE TITLE
How do I extend AFLNet with QUIC and QUIC related protocols?

### ISSUE THREAD

**Issue by Nyte-BK201** [aflnet/aflnet#120]
I am new to stateful protocol fuzzers and AFLNet looks like a big project.
I have checked ProFuzzBench and I would like to have AFLNet running on recent QUIC implementations.
So can anyone tell me how I start and how much the workload is?

**Comment by thuanpv** [comment]
Hi. Adding QUIC support seems very interesting. I think the most time-consuming part could be to read and understand the protocol itself. After that, you can just follow the instructions in README.md to add support for it. Basically, you need to write two functions to extract request sequences from the captured traffics (as seeds) and then extract "response code" from the server response. If the protocol does not have explicit response codes, you can follow approaches that have been use to fuzz the SSL protocol: you extract some parts from the message and calculate a hash value which can be used as the response code. If you have questions, please follow up.
