### ISSUE TITLE
Very low coverage

### ISSUE THREAD

**Issue by Kingrainfish** [aflnet/aflnet#122]
Hi. I  tested snap7 and UDP-based protocols with AFLNET, and both showed very low coverage(map density), staying at 0.02%. Can you provide solutions? Thank you.

**Comment by thuanpv** [comment]
Hi. Snap7 seems to be a very interesting target. Unfortunately, I haven't tested it, and it is very unlikely that I have time to do that, so I cannot say your results are normal or not.

Maybe you can try to make sure that:
- You captured good seeds
- You managed to disable things that introduce randomnesses in the codebase (eg., random session id, nonce). To check that, you can use aflnet-replay to replay the first test in the replayable-queue folder, which should be the replayable version of your first seed, and see if aflnet-replay successfully reach your expected states.

I hope it helps.

**Comment by Kingrainfish** [comment]
Thank you very much.

**Comment by Tongxiangwuwu** [comment]
hello,  @Kingrainfish , I am currently using aflnet to extend the s7comm protocol, and I am encountering a situation where the map density is too low, only 0.05%, and my initial seed is also experiencing this situation:
<img width="1614" height="585" alt="Image" src="https://github.com/user-attachments/assets/27d52a94-ff1d-4298-ad4f-16952358e03a" />
