### ISSUE TITLE
afl-fuzz crashes at launch (after latest commit)

### ISSUE THREAD

**Issue by V3rochka** [aflnet/aflnet#127]
Double free following the last [commit](https://github.com/aflnet/aflnet/commit/96b0cab627c32b74c8957246ee3eb0c334d11e72#diff-6b31be60395ec0eb79199e0947205012d89f67cd69bb82c1e8ba499fedaca477)

To reproduce on ubuntu 18.04

```
git clone https://github.com/aflnet/aflnet.git 
cd aflnet; make clean all; 
cd llvm_mode; make 
cd .. ; make install

afl-fuzz -N tcp://127.0.0.1/1
```

![image](https://github.com/user-attachments/assets/14b84c6f-83e2-4bb3-8be9-8403a802a3ea)

**Comment by thuanpv** [comment]
Thank you very much for reporting the issue.

I tested that commit (contributed by an user) and the code also looks reasonable to me.

I will try to double check it soon. Do you receive the same error report when you run afl-fuzz with full arguments?

**Comment by V3rochka** [comment]
The problem occurs because a memory that defined on stack [here](https://github.com/aflnet/aflnet/blob/96b0cab627c32b74c8957246ee3eb0c334d11e72/aflnet.c#L2571) is freed [here](https://github.com/aflnet/aflnet/blob/96b0cab627c32b74c8957246ee3eb0c334d11e72/aflnet.c#L2628). 

The simplest code to describe this behavior (compiled with gcc 11.4 on ubuntu 22.04):
```
#include <stdlib.h>
int main( )
{
    char buf[8];
    char *tokens;
    //This malloc will cause the double free error probably because it affects values of the current stack
    tokens = (char*)malloc(1); 
    free(buf);
    return 0;
}
```

**Comment by ItsMagick** [comment]
I opened pull request for the fix :D

**Comment by thuanpv** [comment]
Thanks @ItsMagick . I have merged your PR.

Hi @V3rochka . Thanks for your elaboration on this. I think the issue here is because I did not call malloc for each element/string in the tokens so it does not make sense to free them one by one.

The two pieces of code you are referring have the same variable names (tokens) but they are local to the functions so I don't think that is the root cause.
