### ISSUE TITLE
Segmentation fault when trying to fuzz uftpd.

### ISSUE THREAD

**Issue by ConstantinBN** [aflnet/aflnet#15]
When trying to fuzz [uftpd](https://github.com/troglobit/uftpd) AFLNet segfaults.
I compiled uftpd like this:
`cd /home/vagrant/uftpd && sudo ./autogen.sh && sudo ./configure --prefix=/usr && sudo make CFLAGS="-g -fsanitize=address" LDFLAGS="-fsanitize=address" CC="/home/vagrant/aflnet/afl-gcc" && sudo make install`
and then executed
`aflnet/afl-fuzz -i in -o out -N 127.0.0.1/9999 -P FTP -m none -- uftpd -o ftp=9999 -n`
as root.
AFLNet reports
`afl-fuzz 2.56b by <lcamtuf@google.com>`
`[+] You have 1 CPU core and 1 runnable tasks (utilization: 100%).`
`[*] Checking core_pattern...`
`[*] Setting up output directories...`
`[+] Output directory exists but deemed OK to reuse.`
`[*] Deleting old session data...`
`[+] Output dir cleanup successful.`
`[*] Scanning 'in'...`
`[+] No auto-generated dictionary tokens to reuse.`
`[*] Creating hard links for all input files...`
`[*] Validating target binary...`
`[*] Attempting dry run with 'id:000000,orig:in'...`
`[*] Spinning up the fork server...`
`[+] All right - fork server is up.`
`Segmentation fault`
and `journalctl | tail` gives
`Jul 14 13:27:59 vagrant kernel: afl-fuzz[24556]: segfault at 0 ip 00007ffff736ea1d sp 00007fffffffdf40 error 4 in libc-2.27.so[7ffff722c000+1e7000]`

**Comment by ConstantinBN** [comment]
I compiled [libite](https://github.com/troglobit/libite) and [libuev](https://github.com/troglobit/libuev) (dependencies of uftpd) as `sudo ./autogen.sh && sudo ./configure --prefix=/usr && sudo make && sudo make install` each.

**Comment by ConstantinBN** [comment]
This seems to be independent of uftpd.
I tried `aflnet/afl-fuzz -i in -o out -N 127.0.0.1/9999 -P FTP -m none -- ./test` with the following C server:

	#include <stdlib.h>
	#include <stdio.h>
	#include <sys/socket.h>
	#include <sys/types.h>
	#include <arpa/inet.h>
	#include <unistd.h>

	int main(){
	  int fd, err, res, newsock;
	  struct sockaddr_in addr, client_addr;
	  char buf[1024];
	  socklen_t addrlen;
	  
	  fd = socket(AF_INET, SOCK_STREAM, 0);
	  if(fd < 0) { return 1; }
	  
	  addr.sin_family = AF_INET;
	  addr.sin_port = htons(9999);
	  addr.sin_addr.s_addr = htonl(INADDR_ANY);
	  
	  err = bind(fd, (struct sockaddr *) &addr, sizeof(struct sockaddr_in));
	  if(err < 0) { return 1; }
	  
	  res = listen(fd, 5);
	  if(res < 0) { return 1; }
	  
	  addrlen = sizeof(struct sockaddr_in);
	  
	  newsock = accept(fd, (struct sockaddr *) &client_addr, &addrlen);
	  if(newsock < 0) { return 1; }
	  else {
		printf("Received connection from %s!\n", inet_ntoa(client_addr.sin_addr));
		res = read(newsock, buf, 1024);
		if(res < 0) { return 1; }
		close(newsock);
	  }
	  return 0;
	}

I compiled it using `aflnet/afl-gcc test.c -o test`. It results in the very same error.

**Comment by thuanpv** [comment]
Hi,

The issue is likely due to the incomplete network argument. Can you try again with -N tcp://ip_address/port_number?

I hope it helps.

Thuan

**Comment by ConstantinBN** [comment]
Thanks, that was it! Maybe this can be caught somewhere?

**Comment by thuanpv** [comment]
Yes, I will add a check for it. Thanks!
