### ISSUE TITLE
Stack Smashing in state_sequence_to_string

### ISSUE THREAD

**Issue by mlgiraud** [aflnet/aflnet#18]
On the current master branch, if the state id is too big, the sprintf call will write 11 or 12 bytes and destroy the stack.
See here: https://github.com/aflnet/aflnet/blob/c8b7e44a5fb669a6641ad97ad5c5a19d9512ca60/aflnet.c#L1416
Changing this to `char strState[12];` should fix the problem.
Also, it might be better to use `snprintf`.

**Comment by mlgiraud** [comment]
The exact same problem exists here: https://github.com/aflnet/aflnet/blob/c8b7e44a5fb669a6641ad97ad5c5a19d9512ca60/afl-fuzz.c#L785

**Comment by thuanpv** [comment]
Thanks, @mlgiraud . It would be great if you could submit a pull request fixing these issues?
