### ISSUE TITLE
What is session_virgin_bits?

### ISSUE THREAD

**Issue by andronat** [aflnet/aflnet#24]
I'm a little bit confused with the purpose of `session_virgin_bits` in these lines [here](https://github.com/aflnet/aflnet/blob/master/afl-fuzz.c#L1092-L1096). What's their purpose? AFAIKT this is a no-op right?

**Comment by andronat** [comment]
I think I just answered the question myself... AFLNet is looping over `trace_bits` so we can detect if the application is still running as the instrumentation of the target will continuously alter `trace_bits` right?

**Comment by thuanpv** [comment]
Yes, you are right @andronat. It is supposed to prevent AFLNet from killing the server under test too early.

**Comment by andronat** [comment]
Thanks!
