### ISSUE TITLE
Support Protocol Q/A

### ISSUE THREAD

**Issue by shtry** [aflnet/aflnet#29]
Hi.

Does the ```AFLNET``` tool support protocols operating in the Data Link Layer and Physical Layer?

Example : CAN Protocol

It seems that only protocols that support the "TCP/IP" transport layer exist.

Thank you.

**Comment by thuanpv** [comment]
Hi,

Yes. Currently AFLNet focuses on protocols at the application layer.

Thuan

**Comment by shtry** [comment]
Hi. @thuanpv 

Are there any additional protocol development guides?

**Comment by youngcraft** [comment]
This tool support which protocol? Only FTP ...... Do this project has a list of protocols? eg

**Comment by thuanpv** [comment]
It supports quite many protocols already: FTP, SMTP, TLS, SSH, DTLS, DICOM, DNS, RTSP. More to be added.

**Comment by shtry** [comment]
Hi. @thuanpv 

Thanks for the good answer.

It would be nice if there were other cases besides application layers. worthy of reference.

Example : Bluetooth.

**Comment by thuanpv** [comment]
Hi @shtry 

Thanks for your suggestion. I do have a plan to work on fuzzing for embedded systems where lower-layer protocols like CAN, RS485, I2C, SPI, BLE are pervasive. However, it would take quite a long time. Your contribution is welcome.

Thuan
