### ISSUE TITLE
Is it support no-x86?

### ISSUE THREAD

**Issue by sucof** [aflnet/aflnet#3]
hi, Is it support no-x86?

**Comment by thuanpv** [comment]
Hi,

AFLNet does not add any CPU architecture dependencies to AFL so as long as the target works with AFL, it should work with AFLNet, I think. It would be great if you could share your experience while testing on no-x86 system.

Thuan

**Comment by sucof** [comment]
Thanks, Thuan, I will try it with QEMU mode.
