### ISSUE TITLE
live555 states decomposed patch not working

### ISSUE THREAD

**Issue by harrypale** [aflnet/aflnet#37]
Hello, I'm writing my degree thesis and I am focusing on this project (I would like to implement a new protocol for AFLNet).

I was following the tutorial for live555 (Step 0).
The only different command was:
`patch -p1 < $AFLNET/tutorials/live555/ceeb4f4.patch`
instead of:
`patch -p1 < $AFLNET/tutorials/live555/ceeb4f4_states_decomposed.patch`

The problem is that when I start client to capture data with tcpdump, it doesn't stream:

---

❯ ./testRTSPClient rtsp://127.0.0.1:8554/wavAudioTest

Created new TCP socket 3 for connection
Connecting to 127.0.0.1, port 8554 on socket 3...
...remote connection opened
Sending request: DESCRIBE rtsp://127.0.0.1:8554/wavAudioTest RTSP/1.0
CSeq: 2
User-Agent: ./testRTSPClient (LIVE555 Streaming Media v2018.08.28)
Accept: application/sdp

Received 545 new bytes of response data.
Received a complete DESCRIBE response:
RTSP/1.0 200 OK
CSeq: 2
Date: Wed, Feb 03 2021 08:53:25 GMT
Content-Base: rtsp://127.0.0.1:8554/wavAudioTest/
Content-Type: application/sdp
Content-Length: 377

v=0
o=- 1612342402140975 1 IN IP4 192.168.0.50
s=Session streamed by "testOnDemandRTSPServer"
i=wavAudioTest
t=0 0
a=tool:LIVE555 Streaming Media v2018.08.28
a=type:broadcast
a=control:*
a=range:npt=0-5.044
a=x-qt-text-nam:Session streamed by "testOnDemandRTSPServer"
a=x-qt-text-inf:wavAudioTest
m=audio 0 RTP/AVP 10
c=IN IP4 0.0.0.0
b=AS:1411
a=control:track1

[URL:"rtsp://127.0.0.1:8554/wavAudioTest/"]: Got a SDP description:
v=0
o=- 1612342402140975 1 IN IP4 192.168.0.50
s=Session streamed by "testOnDemandRTSPServer"
i=wavAudioTest
t=0 0
a=tool:LIVE555 Streaming Media v2018.08.28
a=type:broadcast
a=control:*
a=range:npt=0-5.044
a=x-qt-text-nam:Session streamed by "testOnDemandRTSPServer"
a=x-qt-text-inf:wavAudioTest
m=audio 0 RTP/AVP 10
c=IN IP4 0.0.0.0
b=AS:1411
a=control:track1

[URL:"rtsp://127.0.0.1:8554/wavAudioTest/"]: Initiated the "audio/L16" subsession (client ports 37578-37579)
Sending request: SETUP rtsp://127.0.0.1:8554/wavAudioTest/track1 RTSP/1.0
CSeq: 3
User-Agent: ./testRTSPClient (LIVE555 Streaming Media v2018.08.28)
Transport: RTP/AVP;unicast;client_port=37578-37579

Received 208 new bytes of response data.
Received a complete SETUP response:
RTSP/1.0 201 OK
CSeq: 3
Date: Wed, Feb 03 2021 08:53:25 GMT
Transport: RTP/AVP;unicast;destination=127.0.0.1;source=127.0.0.1;client_port=37578-37579;server_port=6970-6971
Session: 000022B8;timeout=65

[URL:"rtsp://127.0.0.1:8554/wavAudioTest/"]: Failed to set up the "audio/L16" subsession: 201 OK
[URL:"rtsp://127.0.0.1:8554/wavAudioTest/"]: Failed to start playing session: No RTSP session is currently in progress

[URL:"rtsp://127.0.0.1:8554/wavAudioTest/"]: Closing the stream.

---

The ceeb4f4 patch is working fine, but after more than 5 hours AFLNet didn't find any crash.

Thank you

**Comment by thuanpv** [comment]
In the recently released benchmark (https://github.com/profuzzbench/profuzzbench), a fuzzing setup for Live555 is provided with all instructions (https://github.com/profuzzbench/profuzzbench/tree/master/subjects/RTSP/Live555). Please take a look & run it to see if there is something wrong in your setup.

**Comment by harrypale** [comment]
Hi, the fuzzing works in docker, maybe there is something wrong with my Kubuntu setup, but I have the same problem to record network traffic data with ceeb4f4 states decomposed patch, even in docker.

Maybe I have to record the traffic with ceeb4f4 patch only, and then apply the ceeb4f4 states decomposed patch for fuzzing?
Thank you

**Comment by thuanpv** [comment]
I see. You should record the traffic with ceeb4f4 patch only.
