### ISSUE TITLE
a question about no -E

### ISSUE THREAD

**Issue by whitepoet** [aflnet/aflnet#38]
i have a question.if -E is not enabled, aflnet also will fuzz following the sequence， but how to do the mutation. if -E is not enabled, <M1，M2，M3> will be not use, so what rules will each message in the squence do the mutation?
thanks!

**Comment by acidghost** [comment]
AFAIK this is the code that selects a region to mutate if `-E` is not given: https://github.com/aflnet/aflnet/blob/f2e71ea3347f70afe211de59699371f834976b7c/afl-fuzz.c#L5931-L5937

**Comment by thuanpv** [comment]
Thanks @acidghost . You are right. 

In that case, M2 will be selected randomly. Once M2 is selected, the mutation is done in a similar way. As written in the FAQs section, "If -E is not enabled, even though AFLNet still manages the requests' boundaries information so it can still follow the sequence diagram of the protocol -- sending a request, waiting for a response and so on, which is not supported by normal networked-enabled AFL. However, in this setup AFLNet will ignore the responses and it does not construct the state machine from the response codes. As a result, AFLNet cannot use the state machine to guide the exploration.".

**Comment by whitepoet** [comment]
thanks @thuanpv @acidghost , i get it .
have a happy day!

**Comment by thuanpv** [comment]
Nice! I close the issue now but please feel free to re-open it.
