### ISSUE TITLE
a question about the fuzzing command

### ISSUE THREAD

**Issue by BarbiKod** [aflnet/aflnet#39]
Hello! 
I am a Master student working on my thesis related to AFLNet. 
For getting familiar to how this fuzzer works, firstly I am trying to fuzz a C program, which is a simple echo server/client for testing fuzzers and contains vulnerabilities by design. 
The problem that I am facing is the command I need to use for making the fuzzing. In the example command that you have provided: _afl-fuzz -d -i in -o out -N <server info> -x <dictionary file> -P <protocol> -D 10000 -q 3 -s 3 -E -K -R <executable binary and its arguments (e.g., port number)>_,  do I need to make any changes for fuzzing this simple C program? (After specifying my server info, I do not know and I am not sure how to write the other part of commands.) I have provided a screenshot for that:

![Fuzzing](https://user-images.githubusercontent.com/56866366/111366180-7b302780-8693-11eb-838d-db521325e62c.png)

Also, related to fuzzing ftp, the same commands and the same method should be followed?

**Comment by thuanpv** [comment]
I think the README file contains enough information to answer your questions.
