### ISSUE TITLE
Some doubts about UDP encapsulation

### ISSUE THREAD

**Issue by sucof** [aflnet/aflnet#4]
Hi, Thuan, I have some doubts about UDP encapsulation, when I read your source code, I found AFLNET uses send and recv to wrappers for sending and receiving data over socket, but in UDP communication, recvfrom and sendto are the two functions which are often used, because it is need to know the destination socket address, just use send and recv to wrapper for sending and receiving data, Are there any problems in using UDP?

**Comment by daydayup40** [comment]
Hi, @sucof , I read your issue, but don't know the answer. Could you share why you close this issue?
