### ISSUE TITLE
How to reproduce dnsmasq bugs

### ISSUE THREAD

**Issue by DuckRui** [aflnet/aflnet#48]
Hi，I  read about your paper about fuzzing dnsmasq server(https://github.com/aflnet/aflnet/tree/master/tutorials/dnsmasq).
Now, I get some crashes. But I don't how to reproduce them.I'd appreciate it if you could tell me, think you very much.

**Comment by thuanpv** [comment]
Hi @DuckRui,
Have you tried to use aflnet-replay? Please read the main README to see how it works.
I hope it helps.
Thuan

**Comment by DuckRui** [comment]
Thank you for your reply！ I mean I want to reproduce it without aflnet. Now I have known how to reproduce it.Thanks again

**Comment by DuckRui** [comment]
> Hi @DuckRui,
> Have you tried to use aflnet-replay? Please read the main README to see how it works.
> I hope it helps.
> Thuan

Thank you for your reply！ I mean I want to reproduce it without aflnet. Now I have known how to reproduce it.Thanks again

**Comment by Ricardo-609** [comment]
> 
Could you teach  me the method to reproduce it ? Thanks.
