### ISSUE TITLE
RTSP/1.0 404 File Not Found, Or In Incorrect Format on live555 step1

### ISSUE THREAD

**Issue by cloud0606** [aflnet/aflnet#51]
Hi~👋

When I used the Tutorial - Fuzzing Live555 media streaming server, I couldn't get normal TCP packets in step1.
Here is the server output

![srv](https://user-images.githubusercontent.com/26458003/121203814-fd05aa80-c8a8-11eb-8b85-72a6152f3a78.png)

Here is the client

```bash
cuc@cuc-VirtualBox:~/workspace/live555/testProgs$ ./testRTSPClient rtsp://10.0.2.15:8554/wavAudio
Test
Created new TCP socket 3 for connection
Connecting to 10.0.2.15, port 8554 on socket 3...
...remote connection opened
Sending request: DESCRIBE rtsp://10.0.2.15:8554/wavAudioTest RTSP/1.0
CSeq: 2
User-Agent: ./testRTSPClient (LIVE555 Streaming Media v2018.08.28)
Accept: application/sdp

Received 101 new bytes of response data.
Received a complete DESCRIBE response:
RTSP/1.0 404 File Not Found, Or In Incorrect Format
CSeq: 2
Date: Tue, Jun 08 2021 14:09:59 GMT

[URL:"rtsp://10.0.2.15:8554/wavAudioTest"]: Failed to get a SDP description: 404 File Not Found, Or In Incorrect Format
[URL:"rtsp://10.0.2.15:8554/wavAudioTest"]: Closing the stream.
cuc@cuc-VirtualBox:~/workspace/live555/testProgs$ ./testRTSPClient rtsp://10.0.2.15:8554/wavAudioTest
```
 
![clt2](https://user-images.githubusercontent.com/26458003/121203670-df384580-c8a8-11eb-8a0a-daa97961da8b.png)

It doesn't work to modify the ip 

![clt](https://user-images.githubusercontent.com/26458003/121203654-dcd5eb80-c8a8-11eb-8b23-ff9a4b8d5a00.png)

Using wireshark to view and there is no detailed communication data package. 

![pcap](https://user-images.githubusercontent.com/26458003/121204069-3211fd00-c8a9-11eb-8bf8-5b3e20aa09a8.png)

I strictly  follow the pre-steps to construct it. Is there any other environment needed?😅

**Comment by thuanpv** [comment]
Hi,

Did you run this command "cp $AFLNET/tutorials/live555/sample_media_sources/*.* ./" to copy sample media files to the server working directory?

Thuan

**Comment by cloud0606** [comment]
I did accidentally miss this command😅, and it works after runing this command. 

Thank you very much.

**Comment by B1y0nd** [comment]
thanks!
