### ISSUE TITLE
A question about afl-cov with aflnet.

### ISSUE THREAD

**Issue by DuckRui** [aflnet/aflnet#52]
Hi, I use aflnet to test a network program. When I finished test, I want to use afl-cov to see the coverage of the program. But afl-cov  use stdin or file as input. However aflnet's testcase is network package. 
Can you help me? Thank you very much.

**Comment by DuckRui** [comment]
I mean I noticed that you mentioned the code coverage comparison in your paper. I have a question about how you konw the code coverage. What tools do you use to measure code coverage, can you tell me? Thank you very much.

**Comment by DuckRui** [comment]
> 嗨，我们使用 gcov/gcovr 来衡量代码覆盖率。AFLNet 生成的测试用例包含消息序列，因此您应该使用 aflnet-replay 将它们发送到被测系统，该系统应该使用 gcov 标志进行编译。请查看我们的基准 ProFuzzBench 以获取更多信息：[https](https://github.com/profuzzbench/profuzzbench) : [//github.com/profuzzbench/profuzzbench](https://github.com/profuzzbench/profuzzbench)

Thanks for your reply. I understand it. But if I want know more detailed information like afl-cov (It can provide information about which code was executed and which was not. ).

**Comment by thuanpv** [comment]
In ProFuzzBench setup, we use gcovr and it does produce detailed gcov report containing your expected information (e.g., which code was executed and which was not). Specifically, Please give it a try and check this document to know more about gcovr: https://gcovr.com/en/stable/guide.html
