### ISSUE TITLE
Need for SIP program for fuzzing

### ISSUE THREAD

**Issue by EgodPrime** [aflnet/aflnet#53]
We want to fuzzing SIP protocol with AFLNet, but it's hard to look for a suitable program. Could you help me ? thank you!!!

**Comment by thuanpv** [comment]
Hi @SingleBone. In ProFuzzBench (https://github.com/profuzzbench/profuzzbench), we use AFLNet to fuzz Kamailio SIP Server (https://www.kamailio.org/w/).

**Comment by SingleBone** [comment]
> Hi @SingleBone. In ProFuzzBench (https://github.com/profuzzbench/profuzzbench), we use AFLNet to fuzz Kamailio SIP Server (https://www.kamailio.org/w/).

Thanks!
