### ISSUE TITLE
parallel fuzzing not working

### ISSUE THREAD

**Issue by sgzeng** [aflnet/aflnet#56]
Hi, 

I tried to use completely different configuration for two aflnet instances. However, when one fuzzer is getting seeds from another fuzzer (invoking sync_fuzzers). Segmentation falut happens. Here is the backtrace gdb printed:

```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) **bt**
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f5d8b207859 in __GI_abort () at abort.c:79
#2  0x000055c1d0b3c5c8 in DFL_ck_free (mem=<optimized out>) at alloc-inl.h:150
#3  save_kl_messages_to_file (kl_messages=<optimized out>,
    fname=0x55c1d0e7bbf8 "out-lightftp/afl-slave/queue/id:000002,sync:afl-master,src:000003,+cov",
    replay_enabled=0 '\000', max_count=<optimized out>) at aflnet.c:1458
#4  0x000055c1d0b2d26d in save_if_interesting (argv=0x7ffcb7e294b8, mem=0x7f5d8b57d000, len=76,
    fault=<optimized out>) at afl-fuzz.c:4005
#5  0x000055c1d0b336b1 in sync_fuzzers (argv=0x7ffcb7e294b8) at afl-fuzz.c:7740
#6  0x000055c1d0b14c5a in main (argc=<optimized out>, argv=<optimized out>) at afl-fuzz.c:9169
```
Looking at the code and debug information, I noticed that the variable "kl_messages" is not initialized propley before invoking function "save_if_interesting". Could you take a look? Thanks in advanced!

**Comment by thuanpv** [comment]
Hi @sgzeng . Could you please let me know all the steps I should follow to reproduce this issue?

**Comment by sgzeng** [comment]
Hi. I guess I already fixed it by invoking construct_kl_messages before write_to_testcase in function sync_fuzzers. Could you help me to verify it? thanks!

https://github.com/sgzeng/aflnet/commit/ade8a1207d926afaf9ea811078ced7b29c72d40d

**Comment by thuanpv** [comment]
Hi @sgzeng,
Yes, your patch works well (see dfb5199). Thank you very much for finding and fixing the bug.
Thuan
