### ISSUE TITLE
aflnet(fuzzer) not working.

### ISSUE THREAD

**Issue by dhje0ng** [aflnet/aflnet#58]
I tried purging to the network administrator binary and found the following error:

afl-fuzz 2.56b by <lcamtuf@google.com>
[+] You have 8 CPU cores and 2 runnable tasks (utilization: 25%).
[+] Try parallel jobs - see /usr/local/share/doc/afl/parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[*] Checking core_pattern...
[*] Checking CPU scaling governor...
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning '../dns_testcases/'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,orig:overflow.bin'...
[*] Spinning up the fork server...
[+] All right - fork server is up.

[-]  SYSTEM ERROR : AFLNet - the states hashtable should always contain an entry of the initial state
    Stop location : update_state_aware_variables(), afl-fuzz.c:900
       OS message : No such process
       
 why error message?

**Comment by jhye0n** [comment]
my ubuntu version : ubuntu 20.04.3 LTS (release-x64)

**Comment by B1y0nd** [comment]
@dhje0ng
-m none!!!
command line: afl-fuzz -d -i $AFLNET/tutorials/lightftp/in-ftp -o out-lightftp -m none -N tcp://127.0.0.1/2200 -x $AFLNET/tutorials/lightftp/ftp.dict -P FTP -D 10000 -q 3 -s 3 -E -R -c ./ftpclean.sh ./fftp fftp.conf 2200
Reference1：https://blog.csdn.net/weixin_46483787/article/details/129050230
Reference2：https://blog.csdn.net/qq_28584889/article/details/121207149
