### ISSUE TITLE
Install doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by twoodruff01** [aflnet/aflnet#59]
The readme says to run the following command to install:
```
export PATH=$AFLNET:$PATH
export AFL_PATH=$AFLNET
```

For me, this results in this error when I run try to run this command:
```
gcc -fprofile-arcs -ftest-coverage -g -o fotbot-gcov fotbot.c
```

The error is show here:
![image](https://user-images.githubusercontent.com/71203582/136944100-6f60b59c-2ffe-41c3-b410-ce5aa431bf44.png)

Changing the export to this:
```
export PATH=$PATH:$AFLNET
```
Fixes the issue.

**Comment by thuanpv** [comment]
I have just updated README accordingly so I close this issue now.
