### ISSUE TITLE
there is something wrong when fuzzing, perhaps a bug exists in your code?

### ISSUE THREAD

**Issue by minifish120** [aflnet/aflnet#6]
when it works about 12h, it will abort unexpectedly, as follows:
lq process timing qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqwq overall results qqqqqk
x        run time : 0 days, 12 hrs, 50 min, 11 sec     x  cycles done : 97     x
x   last new path : 0 days, 0 hrs, 10 min, 0 sec       x  total paths : 270    x
x last uniq crash : 0 days, 1 hrs, 52 min, 5 sec       x uniq crashes : 36     x
x  last uniq hang : none seen yet                      x   uniq hangs : 0      x
tq cycle progress qqqqqqqqqqqqqqqqqqqqwq map coverage qvqqqqqqqqqqqqqqqqqqqqqqqu
x  now processing : 265 (98.15%)      x    map density : 1.02% / 1.30%         x
x paths timed out : 0 (0.00%)         x count coverage : 4.73 bits/tuple       x
tq stage progress qqqqqqqqqqqqqqqqqqqqnq findings in depth qqqqqqqqqqqqqqqqqqqqu
x  now trying : havoc                 x favored paths : 21 (7.78%)             x
x stage execs : 61/409 (14.91%)       x  new edges on : 48 (17.78%)            x
x total execs : 117k                  x total crashes : 1436 (36 unique)       x
x  exec speed : 2.25/sec (zzzz...)    x  total tmouts : 35.7k (61 unique)      x
tq fuzzing strategy yields qqqqqqqqqqqvqqqqqqqqqqqqqqqwq path geometry qqqqqqqqu
x   bit flips : n/a, n/a, n/a                         x    levels : 11         x
x  byte flips : n/a, n/a, n/a                         x   pending : 142        x
x arithmetics : n/a, n/a, n/a                         x  pend fav : 0          x
x  known ints : n/a, n/a, n/a                         x own finds : 266        x
x  dictionary : n/a, n/a, n/a                         x  imported : n/a        x
x       havoc : 171/40.3k, 131/71.1k                  x stability : 100.00%    x
x        trim : n/a, n/a                              tqqqqqqqqqqqqqqqqqqqqqqqqj
mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj          [cpu000: 53%]
[-] PROGRAM ABORT : Bad alloc request: 1073741828 bytes
    Stop location : DFL_ck_realloc(), alloc-inl.h:197

Aborted

**Comment by thuanpv** [comment]
Thank you for reporting this. It looks like a bug in the code. Can you please tell me the steps you followed to trigger this bug? Basically, I would like to know what server you have tested and the fuzzing command line .

**Comment by minifish120** [comment]
it happened when fuzzing dtls-server （you supported）and samba （i installed）




| |
于颖超
邮箱：yuych830305@163.com
|

签名由 网易邮箱大师 定制

On 04/29/2020 21:41, Thuan Pham wrote:

Thank you for reporting this. It looks like a bug in the code. Can you please tell me the steps you followed to trigger this bug? Basically, I would like to know what server you have tested and the fuzzing command line .

**Comment by thuanpv** [comment]
Hi,

Have you been able to fix the bug yourself? I am busy recently so I haven't investigated it yet. If you have fixed it, it would be be great.

Thuan

**Comment by thuanpv** [comment]
Hi @minifish120. I have tried to run DTLS fuzzing for 24 hours but I could not reproduce the bug. It would be great if you could share with me your SMB fuzzing setup, via email, so I can try on that. Thanks.

**Comment by thuanpv** [comment]
A quick update. I have run DTLS fuzzing for 2 days and AFLNet does not crash. The fuzzing works fine with 45+ unique crashes found. It seems that the bug is a rare bug and your SMB setup could be very helpful to identify and fix it.

**Comment by thuanpv** [comment]
I haven't heard back from you for quite some time so I close this issue now. Please feel free to re-open it. Thanks.
