### ISSUE TITLE
Where is the LearnLib part of the afl-net?

### ISSUE THREAD

**Issue by behnamben** [aflnet/aflnet#61]
As its mentioned in the paper there is a module using learnlib to use ML to learn the states of the protocol. Therefore, Im trying to use afl-net but I dont know where is the learnlib module so I can modify it.

**Comment by mboehme** [comment]
AFLNet does not use LearnLib. Can you point us to the text that mentions this?

**Comment by mboehme** [comment]
Yes, AFLNet learns the IPSM but in a fairly lightweight manner. We are not using LearnLib :)

**Comment by behnamben** [comment]
Sorry but can you point the exact place in the code where aflnet learns the protocol using ML?
