### ISSUE TITLE
Is it possible to only change the sequence of messages in AflNet?

### ISSUE THREAD

**Issue by behnamben** [aflnet/aflnet#64]
I'm trying to find a way to not mutate the messages while fuzzing, but only change the sequence of recorded messages while fuzzing. Are there any options I can use?

**Comment by thuanpv** [comment]
Hi @behnamben. Yes, I think you can do that with some small changes to the code. Currently, AFLNet follows the stacking mutations approach of the vanilla AFL so it does several mutations at once. If you just want message reordering and/or other high-level mutation operators, you can disable bit flips etc. This loop controls the stacking mutations: https://github.com/aflnet/aflnet/blob/master/afl-fuzz.c#L6994. I hope it helps. Thuan
