### ISSUE TITLE
Fuzzing example fail

### ISSUE THREAD

**Issue by gcc17** [aflnet/aflnet#73]
Hi! Thanks a lot for your efforts! 
When I ran the fuzzing example in the README, it did not work. The output error information is as follows. 
![f6fdc0793efc19ccec5851f79b5b1c5](https://user-images.githubusercontent.com/46296716/171925448-0588398c-e28f-4161-bc7f-4207c935ec9f.png)
When I check the '-N' command, it seems that it is not the _netinfo_ in the README.
![26d6d4702f5bc9f939c3508be4cf412](https://user-images.githubusercontent.com/46296716/171925615-cdcec3b0-2e3f-420e-b6f8-e46979ec1847.png)

Could you help me on the error? Thanks a lot!

**Comment by mboehme** [comment]
-N is just a flag and does not take a parameter. Since the subsequent string (tcp://...) is not a recognized AFLNet option, it will consider this as the program to be run. Since it is not a program, you see this output. My first suggestion would be to remove tcp://... from the command line.
