### ISSUE TITLE
Compiled with AFL tools or default tools

### ISSUE THREAD

**Issue by gcc17** [aflnet/aflnet#74]
Hi! When I followed the tutorial on fuzzing different servers, I noticed that sometimes the compilation is done by AFL tools (dnsmasq, ippsample, LightFTP, TinyDTLS), while others just use default tools like cmake (dcmqrscp, live555).

Why there are such differences? I suppose that AFLNet does not need to instrument the server source code, and just uses its state feedback. Thanks a lot!

**Comment by Gordin508** [comment]
Both dcmqrscp and live555 setups apply a patch which changes the compiler to the afl-clang compiler (in the case of dcmqrscp, it sets a cmake option which tells cmake to use the AFL compiler).

Depending on how the original makefile looked, the compiler is set in different ways: Sometimes by directly patching the makefile, sometimes by simply calling `CC=afl-clang-fast make clean all`.

**Comment by gcc17** [comment]
I see. Thanks!
