### ISSUE TITLE
question about target protocol

### ISSUE THREAD

**Issue by 50u1w4y** [aflnet/aflnet#79]
Hello, thanks for your awesome work.

As I know, IPP is a printer protocol, which means that we need a emulator environment to run the printer firmware and the firmware should be closed source. So, aflnet should be not easily to test IPP protocol.

May I ask you that what target(software) do you choose for IPP protocol fuzz? Is there any printer emulator software which can run directly on Linux?

**Comment by thuanpv** [comment]
We have not tested IPP protocol yet so I cannot suggest any emulators. However, you might be able to use AFLNet to test the real printer directly following the instruction in this un-merged PR for remote-only-mode: https://github.com/aflnet/aflnet/pull/67

**Comment by 50u1w4y** [comment]
thanks for your answer, I got it.
