### ISSUE TITLE
update_state_aware_variables(), afl-fuzz.c:900

### ISSUE THREAD

**Issue by a1819644** [aflnet/aflnet#82]
**Currently facing this is issue and have no idea what causing it.** 

_Any help would be greatly appreciated._

**Comment by a1819644** [comment]
![Screen Shot 2022-08-24 at 10 30 16 pm (2)](https://user-images.githubusercontent.com/88136301/186425949-1950fe41-3308-4a2a-98ba-761283a36965.png)

**Comment by thuanpv** [comment]
Hi. Normally the issue could happen if AFLNet cannot talk to the server under test. I would suggest that you try to run tcpdump to listen to the same port and analyze the captured data.
