### ISSUE TITLE
Import the SUT's state model from the outside

### ISSUE THREAD

**Issue by cristiandaniele** [aflnet/aflnet#87]
Is it possible to import the Software Under Test's state model before starting the fuzzing process?

**Comment by thuanpv** [comment]
Hi,

AFLNet does not support that feature yet but I believe it can be done with some changes. Basically, you can let AFLNet take a state model but no seed input is attached to state nodes initially. When you start the dry-run phase and fuzzing phase, seeds & newly generated inputs can be attached to nodes. When you select a state/node on the state model to do targeted search, you can check if there are some seeds attached to that node. If not, you can skip. Does it make sense?

I hope it helps.

Thuan

**Comment by cristiandaniele** [comment]
Hi, 

thank you for the prompt reply! 

Yes, it makes sense; I might skip the node, or try other seeds (attached to other nodes perhaps). 

Thanks,

Cris

**Comment by thuanpv** [comment]
Since my suggestion makes sense to you, I close this issue. Please feel free to reopen it.
