### ISSUE TITLE
#found a bug

### ISSUE THREAD

**Issue by mozz85** [aflnet/aflnet#88]
# bug description:
Didn't initialize to zero when passing the parameter "region_count"  to function "extract_requests()" 

branch: master
commit id : c2714e9
file : afl-fuzz.c 
line: 5410

**Comment by mozz85** [comment]
It will cause problem when someone try to add support for another protocol, and he didn't set it to zero before using it.
and that's me :)

**Comment by thuanpv** [comment]
Thanks @mozz85 for reporting this issue!!
