### ISSUE TITLE
ForHelp: Can't get response from http server

### ISSUE THREAD

**Issue by Squirre17** [aflnet/aflnet#95]
```shell
[!] WARNING: The target binary is pretty slow! See /usr/local/share/doc/afl/perf_tips.txt.
[+] Here are some useful stats:

    Test case count : 1 favored, 0 variable, 1 total
       Bitmap range : 583 to 583 bits (average: 583.00 bits)
        Exec timing : 6.37M to 6.37M us (average: 6.37M us)

[+] All set and ready to roll!

[-]  SYSTEM ERROR : No server states have been detected. Server responses are likely empty!
    Stop location : main(), afl-fuzz.c:9249
       OS message : Connection refused
```

this is my aflnet launch command
```shell
sudo /home/squ/proj/aflnet/afl-fuzz -t 10000 -m 4000 -d -i in -o out -N tcp://127.0.0.1/80 -P HTTP -D 10000 -q 3 -s 3 -E -K -R "/path/to/httpserver"
```

this is my init corpus
![image](https://user-images.githubusercontent.com/79578430/230588336-591b9035-aac2-48db-9c11-91baa8cca984.png)
I write a py script to test this corpus and get 404 response successfully. But Why it not work on aflnet.....

**Comment by thuanpv** [comment]
Hi. Have you implemented a parser to extract the response code from server responses? It seems you have done so and added an option for the HTTP protocol but I just want to double check first.

**Comment by thuanpv** [comment]
I close this issue because it is not active for more than 1 year.
