### ISSUE TITLE
can't make llvm_mod

### ISSUE THREAD

**Issue by Arashimu** [aflnet/aflnet#97]
I had installed llvm15.0 and clang15.0 version. When I cd llvm_mode and make, it works error.How could I solve it?

**Comment by bond187** [comment]
I have llvm10 on my machine, and I was having the same issue. I ran `export LLVM_CONFIG=llvm-config-10` and that solved the issue for me. Probably you can use `llvn-config-15`.

**Comment by thuanpv** [comment]
I normally follow the approach that bond187 has shared.
